### ISSUE TITLE
[feature request]: 提供解析 excel 文件函数

### ISSUE THREAD

**Issue by eviIIt** [FEMessage/excel-it#25]
**Is your feature request related to a problem? Please describe.**

- 需求有场景为 选择xlsx文件和拖拽xlsx文件 到指定区域, 获取xlsx文件内数据, 用于筛选数据来最终确认提交.

![image](https://user-images.githubusercontent.com/53422750/66824977-eb58ec00-ef7b-11e9-8d0d-493142802dab.png)

目前没有拖拽文件获取数据的功能

**Describe the solution you'd like**

提供 `parseExcel` 函数，则用户可以这样解决上述：

- 自行编写 input 监听拖拽事件
- 传递事件文件
- 使用 parseExcel
- 获得 xlsx 数据

```ts
import { parseExcel } from '@femessage/excel-it'

parseExcel(file, [], data => {
  // I got my xxx.xlsx `data`
})
```

**Comment by levy9527** [comment]
可以
